spring:
  datasource:
    url: jdbc:mysql://localhost/iptg?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  application:
    name: "madoka-generator"
  jpa:
    database: mysql
    show-sql: false
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: false
      hibernate.jdbc.time_zone: UTC

server:
  port: 3321

generator:
  template:
    base-path: mybatis-plus
    output-paths: |
      Model.java.vm: main/java/{packagePath}/model/{className}.java
      Mapper.java.vm: main/java/{packagePath}/dao/{className}Mapper.java
